[package]
name = "rustbucket"
version = "0.0.1"
authors = ["BlueSpaceCanary"]
edition = "2018"

[dependencies]
irc = "0.13"
rand = ""
rand_xorshift = ""
rand_core = ""
ratelimit = "0.4"

# certs &c
openssl-probe = "0.1"